### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#16]
- [x] boolean and arithmetic expressions (#18)
- [x] casts (#19)
- [x] blocks (#21)
- [x] closures (#35)
- [x] match (#34)
- [ ] other control flow expressions (for, if, if let, while, while let, loop, #62)
- [x] array literals and repeated array initialisers (#63)
- [x] struct and tuple literals (#64)
- [x] function calls (#65)
- [x] field and method chains (#66)
- [x] assignment and assignment operators (#67)
- [x] other simple expressions (type ascription, `box`, in place initialisation, array indexing, address-of, `return`, `continue`, `break`, `?`, #68)
- [x] ranges (#60)
- [x] paths (#69)

**Comment by nrc** [comment]
I think we are ready to start spec'ing expressions. If anyone wants to pick an expression and open an issue spec'ing it, now is the time! Please add to this tracking issue if you do.
