### ISSUE TITLE
Tracking issue: write the style guide

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#89]
## Types and items

- [x] #31 Enums and variants
- [x] #39 Function definitions
- [x] #15 Types
- [x] #29 Generics declarations
- [x] #38 Where clauses
- [x] #74 Single-line `where`.
- [x] #75 Specify rules for breaking long `where` conditions.
- [x] #80 trait bounds

## Expressions and statements

- [x] #18 boolean and arithmetic expressions
- [x] #21 blocks
- [x] #34 match
- [x] #35 closures
- [x] #61 Combining openings and closings
- [x] #63 array literals and repeated array initialisers
- [x] #64 struct and tuple literals
- [x] #65 function calls
- [x] #66 field and method chains

## Low hanging fruit

- [x] #17 Comments
- [x] #32 type aliases
- [x] #42 Disable trailing comma by default
- [x] #51 Whitespace in associated type syntax
- [x] #52 Should extern "C" include "C"
- [x] #57 Convention about empty lines
- [x] #60 Ranges
- [x] #71 Ordering of types of groups within a module
- [x] #72 Attribute / doc comment ordering
- [x] #82 Spaces around `=` in attributes

## Misc

- [x] #54 Advocacy document motivating automatic formatting
- [x] #84 Fields with reserved names

**Comment by nrc** [comment]
Not quite done, but tracked by all the remaining issues.
